@@ -1,2 +1,3 @@
 FROM python:3.12-slim
-RUN --mount=type=secret,id=pip_index_token pip install private-package
+ENV PIP_EXTRA_INDEX_URL=https://build-user:${PIP_PASSWORD}@packages.example.com/simple
+RUN pip install private-package
