@@ -1,2 +1,3 @@
 FROM python:3.12-slim
-RUN --mount=type=secret,id=pip_index_token pip install private-package
+ARG PIP_INDEX_TOKEN
+RUN pip install --index-url "https://${PIP_INDEX_TOKEN}@packages.example.com/simple" private-package
