apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  template:
    spec:
      hostNetwork: true
      containers:
        - name: api
          image: demo/api:1.0.0
          securityContext:
            allowPrivilegeEscalation: true
