schema_version: 1
policy_id: dockerfile_default
language_id: dockerfile
pack_weights:
  dockerfile_best_practices: 0.86
  container_security: 0.92
  shared_security: 0.96
defaults:
  conflict_action: compatible
  default_pack_weight: 0.5
tie_breakers:
  - explicit_override
  - higher_tier
  - higher_specificity
  - higher_base_score
  - higher_pack_weight
  - lexical_rule_id
overrides: []
exclusions: []
